### ISSUE TITLE
Optional position settings or adapt to changed screen size

### ISSUE THREAD

**Issue by csill1634** [andrew-bibb/cmst#103]
It would be great for CMST to better support changing screen resolutions:

CMST currently stores and automatically restores its window position:

    settings->beginGroup("MainWindow");
    move(settings->value("pos", QPoint(200, 200)).toPoint() );

However, this can be inconvenient if  you frequently use different screen resolutions or close CMST on an external monitor. As my WM has no option to reposition off-screen windows, I have to manually edit the CMST config to (0,0) to be able to see the window.

If possible, It would be great if

- CMST defaults to 200,200 or 0,0 if the position is out of the current max resolution or
- CMST could provide a command line switch to overwrite the position

Thanks for considering this!

**Comment by andrew-bibb** [comment]
This is not difficult to implement, in fact it is already in my MBMP media player.  I'm planning the next release for early Fall (maybe late Summer) and I'll try to get this one in.

**Comment by andrew-bibb** [comment]
I've split the option to restore the window geometry out from the `Retain Settings` checkbox.  There is a new box called `Retain State`.  When that box is checked the window size, position, and current page will be restored next time you start.  If the box is not checked the default position at 200,200 will be used.  

I'm thinking about the command line switch override.  I've got to get a better handle on how I want to tackle the problem before I start hacking away at the code.  If the switch is just for the window size and geometry that is easy, if we also want it for the other settings (and I'm thinking I might) it will take a bit more as that stuff is spread all over the constructor.

**Comment by csill1634** [comment]
great! Thank you very much!

**Comment by andrew-bibb** [comment]
Got the command line switches done.

-b will bypass Retain State (window size and position)
-B will bypass all the other start options set in Preferences

I'm going to close this one out now.  If something is not working please reopen, or start a new issue if there is something else you feel we should have.
