### ISSUE TITLE
Cannot trigger a post connection script with cmst

### ISSUE THREAD

**Issue by fguzm** [andrew-bibb/cmst#113]
need it for ddclient to run

**Comment by andrew-bibb** [comment]
You are correct, you cannot from CMST. Got a question though so I know where to add this.  Do you need the script to run every time connman makes a connection or just the first time for any given connection?  I've never heard of ddclient so I did a search and I'm afraid I'm not anymore enlightened.  

Anyway it should be easy enough to allow users to trigger any program they feel like after a connect.  I just need to know if it has to be done at every new connection or just the first time for any connection.

**Comment by agaida** [comment]
hi, it is a good working client/daemon for dynamic DNS - and such a trigger would be nice, but isn't a must have i guess.

Package: ddclient                        
Description: address updating utility for dynamic DNS services
This package provides a client to update dynamic IP addresses with several dynamic DNS service providers, such as DynDNS.com. 
This makes it possible to use a fixed hostname (such as myhost.dyndns.org) to access a machine with a dynamic IP address. 
This client supports both dynamic and (near) static services, as  well as MX record and alternative name management. It caches the address, and only attempts the update when it has changed.
Homepage: http://ddclient.sf.net

**Comment by andrew-bibb** [comment]
I was somewhat curious about connman being able to manage the dynamic DNS.  There is a huge amount of network stuff I don't understand, and in the case of ddclient have never heard of.  I have however read most of the connman API documents and don't recall anything about triggering after a connect. Connman will allow you to set nameservers, timeservers and search domains for each connection (and CMST has editing dialogs for each plus dozens of other settings), but I'm not sure any of that duplicates what ddclient is for.   

Should be real easy to implement.  Just need to have the user define a process if he chooses and then trigger it after I get a state change into the Ready or Online state from connman.  Probably take me about half an hour to put in and a bit more after that to test it (well also the time to work on it and that may be a few days yet).  Really just need to know if this is a one shot deal or after every connect.

**Comment by hagabaka** [comment]
DynDNS.com lets you have a domain name pointing to a dynamic IP address. For it to work, you tell it your IP whenever it changes, and ddclient is used for this. So in short, for this use case, it's useful to have a script triggered whenever connman creates a new connection.

You could duplicate NetworkManager's dispatcher script functionality, which if I remember correctly, runs a script with arguments "interface", "up/down", "network name" whenever a connection or disconnection occurs.

**Comment by fguzm** [comment]
As I do not run ddclient in daemon mode, I need to run the script (or directly the program ddclient) after every new connection. (I only connect when I need to be online, I'm offline the most time.)

**Comment by agaida** [comment]
@hagabaka it's not only about DynDNS.com, its for every provider that uses this protocol:
<pre>
protocol=dyndns2
server=dyndns.strato.com
</pre>
i use it to redirect some subdomains from my provider to my homeserver - and it is a pretty cool feature and really useful.

**Comment by andrew-bibb** [comment]
I've updated and uploaded to GitHub code which should allow you to call an external program after connect.  To access this you need to have the "Advanced" checkbox checked.  When you do that a QLineEdit should open up that will allow you to enter the name of the command you want. If there are any command line arguments just provide them as well (space separated).

I'll probably continue to touch up the UI, but if one of you guys could let me know if it works for you I'd appreciate it.  Works here (I tested by having it call a BASH script).

**Comment by fguzm** [comment]
Nothing opens up here... No entry field or something like this. ??

**Comment by fguzm** [comment]
Works, thank you!

**Comment by andrew-bibb** [comment]
I cleaned up some of the "What's This" text for the new control,  Since it works I'm going to close this one out.
