### ISSUE TITLE
Please change the License to expat, if possible

### ISSUE THREAD

**Issue by agaida** [andrew-bibb/cmst#114]
Reasons: https://en.wikipedia.org/wiki/MIT_License#Various_versions

**Comment by andrew-bibb** [comment]
Meant to reply earlier that I'll take a look.  My first brief glimpse seemed to be that this is the same thing with just a more explicit name.  If that is really the case I can probably do that.

**Comment by agaida** [comment]
it is - and it make the licensing clearer
