### ISSUE TITLE
CMST Tray Icon missing when connected to VPN

### ISSUE THREAD

**Issue by flamusdiu** [andrew-bibb/cmst#120]
Using LXQT desktop, when you connect to a VPN, you get a blank icon.
![screenshot-6df1f022](https://cloud.githubusercontent.com/assets/1879197/11459469/21ffa8d6-96a5-11e5-98a4-22b36e47982c.png)

**Comment by andrew-bibb** [comment]
I've not (yet) implemented any of the Connman VPN API into CMST.  I'm actually surprised you were able to get a connection with it.  

The VPN pieces are, I believe, the last non-experimental part of Connman that I still need to work on or implement into the program.  I'm going to keep this issue active until I get that done.

**Comment by flamusdiu** [comment]
Ahh, that's why the CMST won't connect inside the GUI. I connect using the commandline using `connmanctl connect <vpn_name>`

**Comment by andrew-bibb** [comment]
I just uploaded to GitHub code that will manage (connect and disconnect) already provisioned VPN services.  There is a whole new tab in the dialog called VPN, and the tray icon should now display when a VPN is connected.  Using the default icon set it is a lock symbol, "network-vpn" in Adwaita, and "emblem-locked" in Oxygen. 

The VPN page is probably alpha stage.  The favorite icon is really stupid, and I should (and will) use the available space to show some useful information about the service.  If there is something you think would be good or useful to show let me know as now is the time to build it in.

**Comment by flamusdiu** [comment]
I'll take a look at it. Probably need to play with it on my laptop since I VPN more then then on my desktop. I'll let you know.

**Comment by andrew-bibb** [comment]
I'm pretty much wrapped up with the VPN stuff.  Haven't packaged for a release yet, but all the pieces are now on GitHub.  I'm going to close out this issue now.  Next release will have all the VPN stuff included.

**Comment by flamusdiu** [comment]
@andrew-bibb you're great! Sorry, I have been swamped with homework lately. =(

**Comment by andrew-bibb** [comment]
Oh yes, I remember those days.  Good luck with your studies - keep your mind on what is important (which would not be this).
