### ISSUE TITLE
The device name should be different when you insert usb nic device

### ISSUE THREAD

**Issue by bubbless** [andrew-bibb/cmst#124]
My laptop's PCI NIC interface is break, so I buy a usb nic,but in cmst the deivces name are no different .
They are all call'd Wired. The drifferent is MAC address  like ethernet_`XXXXXXXXXXXX`_cable.
Why not the device name like `eth0`  `wlan0` that `ip link` output? 
In the status window, you can not modify connection information, you must enter the details below modification service.
I also installed `connman-gtk` in AUR.Here is a screenshot of the connman-gtk running
![_2016-01-28_14-29-03](https://cloud.githubusercontent.com/assets/4928187/12638673/13726f7e-c5da-11e5-85b2-e775dd0aa5ba.png)

I propose to modify the device naming，Thanks.

**Comment by andrew-bibb** [comment]
Thank you for the suggestion.  

I've been trying to hold the program output to exactly what Connman returns, so what you'd see in CMST is what you'd see using connmanctl.  I like this idea though, especially for the tray icon popup menu, and probably an add to the first tab services box.

Let me see what I can do along these lines.

**Comment by andrew-bibb** [comment]
Before I get too far into is something like this about where we want to go?   Wifi connections are named so naming like "wlan0" seemed like we were going in the wrong direction.  What I did do however is add "[Hidden]" to the wifi service name if the wifi connection is hidden.  Before it would just be blank.

![pic01](https://cloud.githubusercontent.com/assets/6935544/12692064/7f267ce2-c6c0-11e5-8e59-5ab64babe192.png)

**Comment by andrew-bibb** [comment]
I'm going to close this one out for now.  If you think we still need work on it please feel free to reopen it.
