### ISSUE TITLE
Preferences look strange if advanced controls enabled

### ISSUE THREAD

**Issue by agaida** [andrew-bibb/cmst#129]
http://i.imgur.com/1k7wN64.png - make the window bigger per default would fix that

**Comment by andrew-bibb** [comment]
Looks like I didn't put those into a layout, should be fairly to fix.  Thanks for finding it, as without a layout it probably does the same thing if you try to shrink the window by dragging the lower right corner up.

**Comment by andrew-bibb** [comment]
Bit more complicated was right.  I've got some code up on GitHub now that may address this.  I fear though I may have broken the small screen fix I put in a couple of weeks ago.  If you get a chance to look and see how the current runs I'd appreciate it.

**Comment by andrew-bibb** [comment]
I may have it now.  I added a scroll area to the Preferences tab and removed the fixed size layout (my previous try).  I think this will do it both for your issue and the older display properly on small screens issue.  Code is now here on GitHub.

I'm going to leave this open for another day or two as I may want to do the same on one additional tab.  Other than that I think it is done.

**Comment by agaida** [comment]
looks fine i think - great work so far. Thank you.

**Comment by andrew-bibb** [comment]
Great.  I'm going to close this out for now.  If it comes back or you find something similar feel free to reopen or start a new issue.

I did add scroll areas to a couple of the other tab panes.  The behavior (expand and shrink) now is more consistent across panes so overall it is better.
