### ISSUE TITLE
Reproducible builds

### ISSUE THREAD

**Issue by agaida** [andrew-bibb/cmst#134]
Hi, it might be that you would consider this as a non-issue, all things are fine and build without problem. The minor glitch is, that the builds are not reproducible - the created binary files differ from build to build. This is because the build date and time are compiled into cmst on each build.

I have a patch for that - so the debian versions are reproducible and the QA don't complain about this. I have no problems to apply this every time,  but i dont know if reproducible builds are a goal for other distributions too, so maybe it would be a good idea to integrate this in upstream. What do you think?

**Comment by andrew-bibb** [comment]
I'm not really sure if it is a goal on other distributions, I've never run across it.  Just because I'm not aware of it does not mean it is not a good idea.  Can you post the patch code here and I'll take a look.  So long as it does not change major pieces of the UI or functionality I'm fairly sure I'll be good with it.

**Comment by agaida** [comment]
it will only remove the buildtime/date from the info - and that will make the build reproducible.

**Comment by andrew-bibb** [comment]
I'm still not clear on what I need to change.

**Comment by agaida** [comment]
Sorry, did not forget you but was a little bit busy:
```
Description: Remove __DATE__ and __TIME__ macros to archive reproducible builds
Author: Alf Gaida <agaida@siduction.org>

--- cmst-2016.01.28.orig/apps/cmstapp/code/control_box/controlbox.cpp
+++ cmst-2016.01.28/apps/cmstapp/code/control_box/controlbox.cpp
@@ -429,14 +429,11 @@ void ControlBox::aboutCMST()
                   "<center>sqozz (German)"
                   "<center>Ilya Shestopalov (Russian)"
                   "<br><center><b>Build Information:</b>"
-                  "<center>Compiled using QT version %5"
-                  "<center>Built %6 - %7")     .arg(TranslateStrings::cmtr("cmst"))
+                  "<center>Compiled using QT version %5")      .arg(TranslateStrings::cmtr("cmst"))
                                                                                                                                                            .arg(VERSION)
                                                                                                                                                            .arg(RELEASE_DATE)
                                                                                                                                                            .arg(COPYRIGHT_DATE)
-                                                                                                                                                           .arg(QT_VERSION_STR)
-                                                                                                                                                           .arg(__DATE__)
-                                                                                                                                                           .arg(__TIME__) );
+                                                                                                                                                           .arg(QT_VERSION_STR));
 }

 //
```
Basicly thats all - with the  macros the binaries will difer every build.

**Comment by andrew-bibb** [comment]
Sorry, didn't mean to push, I just was not clear what you wanted done.  I had forgotten I had put those lines in.  They mainly there to help me in answering issues here so I could know when (and with what QT version) the program was compiled against.  

Anyway they are commented out now.  I may isolate them in a preprocessor #if directive if I can find some way of making sure I don't forget to remove it when I do a release.  I'm dubious about that proposition, so the smart money would be they stay commented until I forget about them.
