### ISSUE TITLE
AppData file for cmst Gnome desktop

### ISSUE THREAD

**Issue by martinkg** [andrew-bibb/cmst#135]
please add the following cmst.appdata.xml for gnome desktop.

http://fedoraproject.org/wiki/Packaging:AppData
http://people.freedesktop.org/~hughsient/appdata/

please store the file under
misc/appdata/cmst.appdata.xml
[cmst.appdata.xml.txt](https://github.com/andrew-bibb/cmst/files/145199/cmst.appdata.xml.txt)

**Comment by andrew-bibb** [comment]
Copywrite and licence will need to be changed (this project is MIT-Expat).  Do you want me to do that or would you rather?

Also do you need modifications to the qmake file to install this when somebody runs 'make install' ?  If you need it let me know I'll add it in, unless you are good with hacking qmake files.

**Comment by martinkg** [comment]
thanks for your feedback, please could you change the license to MIT and add the modifications to
add install the file via 'make install'
thanks Martin

**Comment by andrew-bibb** [comment]
Think I've got it all.  If there are any problems let me know.

A-
