### ISSUE TITLE
When I connect  WIFI always alert error: org.freedesktop.DBus.Error.NoReply

### ISSUE THREAD

**Issue by bubbless** [andrew-bibb/cmst#143]
#### When I change an access points will be alert  a dbus warning, but  confirmed the warning, WIFI connection is active,and working fine.
![_2016-04-28_18-29-25](https://cloud.githubusercontent.com/assets/4928187/14883301/23b4a194-0d70-11e6-9f73-7be6ecce5a6c.png)

* I'm now using Version:  `2016.04.03-1`

![_2016-04-28_18-36-42](https://cloud.githubusercontent.com/assets/4928187/14883319/4b4879ce-0d70-11e6-9e43-822ee2b16c09.png)

* The release Version : `2016.01.26 ` no such warning.
* In issue #111 , I trying to using connmanctl connect WIFI manually ,but no error alert.
* I'm using Archlinux & Xfce, QT version ` 5.6.0` ,connman version `1.32`
```
systemctl |grep dbus
dbus.service              loaded active running   D-Bus System Message Bus
dbus.socket               loaded active running   D-Bus System Message Bus Socket

```

**Comment by andrew-bibb** [comment]
Thank you, this should give me what I need to track it down. I'm pretty sure it is a timeout issue, nothing to do with dbus not actually running.  Thought I had corrected this in 2016.04.03, it was introduced between 2016.01.26 and 2016.04.03.

I'm actually at work at the moment, but I'll dig into it this evening.  Thank you for reporting getting me this good information to work with.

**Comment by andrew-bibb** [comment]
I got a bit hung up this evening, but managed to dig into the code some.  I do have a check to capture the NoReply error, at least where I think it is occuring.

Can you tell me exactly what buttons or controls in CMST you are using and in what order when this shows up. I can't reproduce this here. I do set the timeout (5 milliseconds) on the method call just before the error capture.  That may be it, but before I start playing with it I'd like to understand exactly what you are doing.

**Comment by bubbless** [comment]
* I recorded a video,I try to convert to gif,but poor,So compressed into ZIP.
* When I Right-click the system tray,change WIFI,will alert the warning.
  But in main window has no warning.
* Sometimes the WIFI list  only one ? I have to Rescan.

[vokoscreen-2016-04-29_11-03-48.mkv.zip](https://github.com/andrew-bibb/cmst/files/241749/vokoscreen-2016-04-29_11-03-48.mkv.zip)

**Comment by andrew-bibb** [comment]
Connecting and disconnecting from the system tray was the key.  I had not captured the dbus reply from the function to handle that.  Actually I had even forgotten you could connect and disconnect from the system tray, I personally never use it and really did forget that I put that in there.

I just uploaded code to GitHub (2016.04.29-1) which should fix this for you.  If not please feel free to reopen this.

Your comment about having to rescan - that is a Connman thing.  Eventually the Connman autoscan (I can't control that) will pick up AP's, or at least it does here.  If there is one out there that you know is there and it does not show up when you need it,  the manual rescan is the only thing you can do.
