### ISSUE TITLE
"Could not create an interface to connman-vpn on the system bus" when connman built with --disable-openvpn

### ISSUE THREAD

**Issue by benkohler** [andrew-bibb/cmst#144]
I build connman with --disable-vpn since I don't use that feature.  Recently cmst has started throwing a scary looking warning when I start it up, I believe it was caused by commit 65b13eac667e705e1d0f4758b6a06ec3ffcaa781.  Would it be possible to hide this for people who have purposely built connman w/o vpn support?

Thanks!

**Comment by andrew-bibb** [comment]
The current version here at GitHub (2016.04.28-1) should fix this for you.  A new commandline switch -n (--disable-vpn) has been added.  You can also access this from the preferences tab.  Note that it is a start option so if you use the checkbox in the preferences tab you have to exit the program and start it again before it will take.  When this option is set CMST will bypass establishing a connection to connman-vpn and will disable (gray out) the vpn controls.  

I've compiled with VPN so I can't completely test it, but I'm pretty sure it will do what you need.  If not feel free to reopen this issue.

Thanks for reporting it.
