### ISSUE TITLE
Time server can not type domain?

### ISSUE THREAD

**Issue by bubbless** [andrew-bibb/cmst#146]
Time server can only typing IP Address?
A lot of NTP server only supply domains.
[http://www.pool.ntp.org/zone/cn](http://www.pool.ntp.org/zone/cn)
`1.cn.pool.ntp.org`
`1.asia.pool.ntp.org`
`2.asia.pool.ntp.org`

**Comment by andrew-bibb** [comment]
I just removed the validator from that field.  Can you let me know if the non IP address time server field works from the Connman end?  It was not clear to me from the Connman API documentation that it would or will.  If it does I need to finalize this change and try to put some sort of validator back in.  Also need to do the same in the provisioning editor.  Right now all I've done is disable the validator so you can put anything in the timeserver field.

Thanks
A-

**Comment by bubbless** [comment]
I using Connmanctl to configure just fine.
`connmanctl> config wifi_XXXXXXXXXXxxx_managed_psk --timeservers 1.cn.pool.ntp.org `
![_2016-05-23_17-58-14](https://cloud.githubusercontent.com/assets/4928187/15467266/34f6b326-2110-11e6-9337-3b7d39273454.png)
I can not directly typing domains.

**Comment by andrew-bibb** [comment]
Thanks for checking at the Connman end.  

The code currently in the master branch here at GitHub should allow you to enter anything into the timeserver field.  If that is not working please let me know, but it seemed to test out fine before I uploaded it.  

What I need to do next is see if I can add a domain validator, and remove the validator from the provisioning editor.

**Comment by bubbless** [comment]
Thanks for you commit.Now I can typing domain name,I do not worry about my laptop time became faster.

**Comment by andrew-bibb** [comment]
I just did a commit closing this issue.  Nameserver and timeserver fields will now accept  domain names, IPv4 and IPv6 addresses.
