### ISSUE TITLE
How can I typing multiple IPv4 address?

### ISSUE THREAD

**Issue by whour** [andrew-bibb/cmst#148]
Sometimes I need configuration multiple IPv4 address. Office network maybe 10.0.0.0/24, But access  Internet maybe 192.168.0.0/24, default gateway is 192.168.0.x.
I'm Google the key word 'connman multiple ip address' and I did not find useful information.
Is that Connman can not tying multiple IP?
Now I can only tying `ip address add 10.0.0.x/24 dev wlan` to add IP address.

**Comment by andrew-bibb** [comment]
For any of the fields which take IP addresses (or domains for that matter) you should be able to enter as many as you want space delimited.  You can also use , or ; for a delimiter, but I don't advertise that.  

Is there a specific field where the multiple entries are not working?

**Comment by andrew-bibb** [comment]
This one has been quiet for a bit so I'm going to close it to keep things tidy.  If you feel it should be kept open please do, or let me know and I'll reopen it.

**Comment by whour** [comment]
Recently I need to manually modify the IP address, the host address can not be partially modified, and sometimes the gateway is unnecessary, but do not fill the gateway can not be saved.
IP address bar and can not fill `,` `;`
![2](https://user-images.githubusercontent.com/4928187/32088669-a5d23c08-bb17-11e7-9809-3d88d19afe89.gif)

**Comment by andrew-bibb** [comment]
I've been investigating this and it seems to be the way ConnMan works.  It will only accept the fields if all of them are filled in.  I'm still looking at it and it seems a bit odd as if you set up an external provisioning file the documentation specifically says that Gateway is optional for those.  This dialog modifies the ConnMan generated settings file which is different.  

As I said above, I'm still looking at it.  May have to dig into the ConnMan source code next.

**Comment by andrew-bibb** [comment]
Scratch what I just wrote, it is me.  I was creating a DBus dict assuming all fields were necessary.  If Gateway is specified in the dict the value cannot be empty or ConnMan will reject it.  Fix will be up shortly.

**Comment by andrew-bibb** [comment]
Just uploaded a fix for the IPv4 part.  Still need to do the same for IPv6 and I realize I need a bunch of additional validators to make sure that address and netmask are both filled in as when one is filled in both must be.  I also want add some features to show the manual configuration boxes only when manual configuration is selected.  They should be hidden when DHCP or off are selected, so I am going to leave this open until I get that part done.

**Comment by whour** [comment]
Thanks for your hard work.
