### ISSUE TITLE
CMST proxy showing wrong fields

### ISSUE THREAD

**Issue by klausenbusk** [andrew-bibb/cmst#149]
Hello

I just discovered today. If you open configuration and set proxy method to ex `Auto`, then next time you configuration proxy method is still `Auto` but it shows the field for `Manual`.

CMST version 2016.04.03-2

Regards Kristian

**Comment by andrew-bibb** [comment]
I'm not seeing the behavior with `Auto` and `Manual`, but I am with `Manual` and `Direct`.  Someting appears to be off in that segment of code. 

A tough time of year for me to work on indoor programming, but I'll try to get this resolved before the next release, which I'd still like to do sometime this month.

**Comment by andrew-bibb** [comment]
I was playing around with this one and I may have fixed it.  Seems to work at my end, plus I removed a stray debug statement I didn't realize was still active.

Note that if you select `manual` then you must provide the `Servers` or the selection will not be saved.  This is a ConnMan feature.  `Excludes` is optional.

Version is 2016.08.11-1

**Comment by klausenbusk** [comment]
Can we close this issue?

**Comment by andrew-bibb** [comment]
Can do.  If the problem persists please do not hesitate to reopen or start another issue.

A-
