### ISSUE TITLE
Problem with Progressbars

### ISSUE THREAD

**Issue by tsujan** [andrew-bibb/cmst#159]
Currently, CMST's progressbars use a stylesheet to have a suitable layout. The problem with stylesheets is that they don't match the active widget style and can result in ugly widgets:

![ugly](https://cloud.githubusercontent.com/assets/981076/23008770/2d67ba34-f427-11e6-85d4-d2ef46106bb7.png)

However, the progressbars could be laid out without stylesheets too, so that they are drawn completely by the active widget style:

![good](https://cloud.githubusercontent.com/assets/981076/23008787/3e58b7e4-f427-11e6-9282-68d019fa0557.png)

An example for wireless:
````
      // layout
      QWidget *pw = new QWidget();
      QHBoxLayout *l = new QHBoxLayout(pw);
      l->addWidget(pb04);
      pw->setLayout(l);
      l->setAlignment(Qt::AlignCenter);
      l->setContentsMargins(7, 5, 11, 5); // or (7, 6, 11, 6) as in "signal_bar.qss"
      ui.tableWidget_wifi->setCellWidget(rowcount, 4, pw);
````

I use the latest release; sorry if this is implemented in the latest git version.

**Comment by andrew-bibb** [comment]
Thank you for the suggestion.  I have nothing like this in the works, but I expect I'll be able to do it.

Right now on this program I'm really just monitoring the ConnMan developer mailing list for changes to anything we implement and responding to suggestions such as this.  I'll add it to the list and let you know when it is done.

**Comment by tsujan** [comment]
This isn't important -- it's just about appearance. CMST is already the best connman GUI :)

**Comment by andrew-bibb** [comment]
I just uploaded an attempt at this in a separate branch.  It is in branch issue159.  If you get a chance could you download that branch and see if it does what you want. 

One thing I noticed is that by losing the stylesheets I also lose colorizing the fill of the progress bar to match the colorized icons (if you use that feature).  I'm going to hunt around to see if I can put that back in, but if not no big deal.  

Meant to mention, I'm not sure what you are using for the widget theming, but I really like it.  I'm running a barebones WM with no theming whatsoever.  A lot of what I do is based on that.

A-

**Comment by tsujan** [comment]
> I just uploaded an attempt at this in a separate branch. It is in branch issue159. If you get a chance could you download that branch and see if it does what you want.

Thanks! I'll test it as soon as I find some free time.

> One thing I noticed is that by losing the stylesheets I also lose colorizing the fill of the progress bar to match the colorized icons (if you use that feature). I'm going to hunt around to see if I can put that back in, but if not no big deal.

Oh, I didn't know about colorizing progressbars.

Each style plugin draws progressbars in its own way. My point is just that if progressbars aren't drawn by the style plugin, they might become ugly (the first screenshot above). Some style plugins (like Kvantum) can change the text color inside the progress indicator so that the text is seen clearly. Another screenshot (with KvAmbience belonging to Kvantum) that shows this:

![cmst1](https://cloud.githubusercontent.com/assets/981076/23104865/f57fc848-f6ea-11e6-92ea-35a5fd2e4f1d.png)

If I reverse the changes I made to cmst, the above progressbars will have black text inside indicators and a black border around them.

Of course, stylesheets -- combined with QStyle methods -- can be used in such a way that progressbars are OK with all styles but that would mean a lot of work for a simple goal. IMHO, it's better to let the active style draw progressbars.

BTW, I forgot to say that I could make a PR for this but since you've done it, I'll try that branch soon.

**Comment by tsujan** [comment]
> Meant to mention, I'm not sure what you are using for the widget theming, but I really like it. I'm running a barebones WM with no theming whatsoever. A lot of what I do is based on that.

Sorry, I didn't see this! I use [Kvantum](https://github.com/tsujan/Kvantum). It draws widgets with SVG elements.

**Comment by tsujan** [comment]
OK, I couldn't wait for free time ;) Tested the branch and, yes, that's what I meant.

However, I think you could keep colorization. With some changes to the code, cmst can leave the progressbars to the active style *only* when `ui.lineEdit_colorize->text()` is empty; otherwise, it could use the color and draw progressbars itself. I haven't tested this idea yet but it seems possible.

**Comment by andrew-bibb** [comment]
Super, I'll merge it in.

I spent maybe 45 seconds looking at the color background.  I'm sure I can do it, just not sure if it's worth the time, it is really not that big a deal to me.

Anyway thank you for the suggestion and for verifying the branch code works.  Anything else you need let me know.

A-

**Comment by tsujan** [comment]
So, you'll keep colorization (as suggested in https://github.com/andrew-bibb/cmst/issues/159#issuecomment-280939773)? I didn't know about it but once you mentioned it, it seemed like a nice feature to me.

**Comment by andrew-bibb** [comment]
Oh sure, I'll try to keep it in.  Probably be a day or two or three before I get it uploaded.

**Comment by andrew-bibb** [comment]
Colorizing bars to match icons is back

**Comment by tsujan** [comment]
Thanks! It works fine. And https://github.com/andrew-bibb/cmst/commit/5be4ce6f9a733e609cfcf37492f5c025f80d36c9 is better than what I had in mind.
