### ISSUE TITLE
make: gtk-update-icon-cache: Command not found

### ISSUE THREAD

**Issue by martinkg** [andrew-bibb/cmst#160]
the build of cmst fails on the Fedora Buildssystem
[build.log](https://kojipkgs.fedoraproject.org//work/tasks/4850/18134850/build.log)

cmst build scripts run gtk-update-icon-cache during the build.

In the context of Fedora packaging, we have the build step and install completely separated and
the icon cache regeneration needs to happen when the binary rpm is installed on the user's machine,
not during the build time. Because of that, I would fix this by just dropping the gtk-update-icon-cache
step from upstream build scripts. Another solution would be to conditionalize it on the existence of DESTDIR, so that when DESTDIR is set, then skip running gtk-update-icon-cache.
This would also work for Fedora.

e.g.

ifeq ($(DESTDIR),)
  desktop.extra = gtk-update-icon-cache /usr/share/icons/hicolor
endif

**Comment by martinkg** [comment]
this is the working patch for compiling in build environment:
```
--- cmst-5be4ce6f9a733e609cfcf37492f5c025f80d36c9/cmst.pro.orig	2017-03-02 20:47:34.985348086 +0100
+++ cmst-5be4ce6f9a733e609cfcf37492f5c025f80d36c9/cmst.pro	2017-03-02 20:48:10.965692212 +0100
@@ -56,7 +56,9 @@
 # desktop file
 desktop.path = /usr/share/applications
 desktop.files = ./misc/desktop/cmst.desktop
-desktop.extra = gtk-update-icon-cache /usr/share/icons/hicolor
+!isEmpty(DESTDIR) {
+	desktop.extra = gtk-update-icon-cache /usr/share/icons/hicolor
+}
 INSTALLS += desktop
 
 # autostart desktop file
```

**Comment by andrew-bibb** [comment]
The patch seemed to work at my end so applied.  Thank you very much for this.  

Was just looking and it seems to be about time to do another release.  I'll try to get one out this weekend and of course this patch will be in it.

**Comment by andrew-bibb** [comment]
Brain dead here - I meant to mention: I've never built for Fedora but if there is anything else you need to make it work let me know.  One that comes to mind are the distro specific roothelper.conf files needed if you want to use the provisioning editor or vpn editor. 

Anyway - anything you need let me know.
