### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by agaida** [andrew-bibb/cmst#168]
Hi, could you please make a new release or fix the release tarball? Source tarballs with included binaries ar enot so nice. Thanks.

**Comment by agaida** [comment]
Suggestion:

Add tar.xz
```
# /etc/gitconfig
[tar "tar.xz"]
command = xz -c
```
Add some files to .gitattributes
```
# We don't want to export README.md and
# building_and_installing.txt
README.md export-ignore
building_and_installing.txt export-ignore
```

Export a release-tarball
```
name=cmst
version=2017.03.18
tag=$name-$version
git archive -v -9 --format tar.xz --prefix $tag/ $tag --output ..//$tag.tar.xz
```

**Comment by andrew-bibb** [comment]
I've got two issues hanging over my head that I'm getting nowhere on.  Both are for ConnMan features that I'm not clear on, and a lot of the holdup is getting the time (few personal things going on at the moment that are real time consumers).

This is fairly simple if I'm reading this right.  Hopefully in the next week or two.

**Comment by agaida** [comment]
Please, no hurry, take your time - i made a new tarball from the release and it is uploaded.

**Comment by andrew-bibb** [comment]
Finally got around to doing the release.  Used your suggestions above, so the new one is in .tar.xz format.  Much easier than how I had been doing it so thank you.

I think all the annoying binaries are out of this.  If I'm wrong and missed one please let me know.

A-
