### ISSUE TITLE
close cmst when close ("x") button pressed

### ISSUE THREAD

**Issue by lllars** [andrew-bibb/cmst#169]
I guess most users of this program run it with a system tray, and so want the program to keep running.  I run openbox without a system tray and would prefer cmst to close when I'm done with it.  I can click the "exit" button and it does just that.  But, if I forget and hit the "x" in the titlebar, the cmst process remains running, and the window dissapears (with no way of getting it back).

Is it possible to add an option (to preferences or on the command line), so the program can be set to exit when closed?  Maybe this behavior should be part of the "--disable-tray-icon" option?

**Comment by andrew-bibb** [comment]
I'm pretty sure I can do this.  I do not quit on last window close (controlbox.cpp line 136). Comments in the code before that explain why.  It indeed is mainly for people running from a systemtray, so it will be fairly simple to put in a systemtray check and if none found bypass that command.

**Comment by lllars** [comment]
Thanks!  The fix works great.
