### ISSUE TITLE
Tray menu renders with a strange dashed line

### ISSUE THREAD

**Issue by Coacher** [andrew-bibb/cmst#170]
![screenshot_20170707_002853](https://user-images.githubusercontent.com/1401448/27933815-9847412e-62ab-11e7-9e25-9d64f783bccf.png)

**Comment by andrew-bibb** [comment]
The dashed line indicates that this is a tear off menu.  If you click the line the menu will detach and you can move it around you desktop wherever you want.

**Comment by Coacher** [comment]
I see. Do you know how I can disable this feature?

**Comment by andrew-bibb** [comment]
Your best bet would be to just not use the feature, it cannot be disabled within the program. Adding a user control to enable or disable it would be so low on my priority list that it would likely never get done.

If you want before you build the program go to cmst/apps/cmstapp/code/controlbox.cpp and change the "true" in line 2484 (current code base) to "false"

`trayiconmenu->setTearOffEnabled(true);`

**Comment by Coacher** [comment]
I hoped there is a way to disable these tear off menus via qt theme.
Using your suggestion I can get rid of this dashed line. Thank you!
