### ISSUE TITLE
Service details always says 'Auto Connect: No' until reboot

### ISSUE THREAD

**Issue by Coacher** [andrew-bibb/cmst#171]
Hello.

Steps:
Details -> [Choose service from drop-down menu] -> Configuration -> [Check AutoConnect box] -> OK

Actual results:
Service description still says 'Autio Connect: No'

Expected results:
Service description is updated and says 'Auto Connect: Yes'.

Additional info.
If I click Configuration again, Autoconnect option is unticked.
/var/lib/connman/[my network]/settings has `AutoConnect=true`

**Comment by Coacher** [comment]
Additional info:
Auto connect setting seem to be displayed properly after reboot.

**Comment by andrew-bibb** [comment]
Can you do me a favor and check this with the latest git version of the program here.  I'm pretty sure this used to do as you said, but I just checked it and it is working properly.  Not sure why, maybe I accidentally fixed it, or maybe a Connman update fixed it, or maybe it is still not working at your end in which case this will be difficult to find.

**Comment by Coacher** [comment]
Tested with connman git and cmst git after wiping all connman configs and the issue is no longer reproducible (though I no longer have access to AP, which caused this issue before). Must be a glitch.
