### ISSUE TITLE
hello, i  meet the same questions  about "Error /net/connman/technology/wifi: No carrier" ,anyone can help?

### ISSUE THREAD

**Issue by ShiyuanSolutions** [andrew-bibb/cmst#174]

**Comment by andrew-bibb** [comment]
First off we need to see if ConnMan can find the wifi service. From a terminal window type the following:
`connmanctl`
`technologies`

Check to see that WiFi is listed. If it says "Powered = False" then type:

`wifi enable`

It should come back with a message saying "Enabled wifi".  If it does that then type:

`scan wifi`

To exit connmanctl type `quit`

If it fails at the "wifi enable" command you may need to use rfkill.  As root or super user:
`rfkill unblock all`.  I have had several fresh installs where rfkill has to be used first (and only once) to enable wifi.  

If the above does not work then there is a problem at the Connman end, not the CMST end.  One additional thing to check is wpa_supplicant.  From a terminal window type:

`systemctl status wpa_supplicant` and see what you get for results.

Feel free to post any output from the above commands you think may be helpful.

**Comment by ShiyuanSolutions** [comment]
hello ,i follow your steps and type the command  "systemctl status wpa_supplicant",  and then get followos as:

soluxz@zktecon:~/workplace/connmanProject/d-feet-0.1.7$ systemctl status wpa_supplicant
● wpa_supplicant.service - WPA supplicant
   Loaded: loaded (/lib/systemd/system/wpa_supplicant.service; disabled; vendor preset: enabled)
   Active: active (running) since 四 2017-07-20 18:17:58 CST; 14h ago
 Main PID: 18227 (wpa_supplicant)
   CGroup: /system.slice/wpa_supplicant.service
           └─18227 /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant

7月 20 22:18:23 zktecon wpa_supplicant[18227]: nl80211: deinit ifname=wlx7cdd90caf78b disabled_11b_rates=0
7月 20 22:19:04 zktecon wpa_supplicant[18227]: dbus: wpa_dbus_get_object_properties: failed to get object properties: (none) none
7月 20 22:19:04 zktecon wpa_supplicant[18227]: dbus: Failed to construct signal
7月 20 22:20:40 zktecon wpa_supplicant[18227]: nl80211: deinit ifname=wlx7cdd90caf78b disabled_11b_rates=0
7月 21 08:49:55 zktecon wpa_supplicant[18227]: dbus: wpa_dbus_get_object_properties: failed to get object properties: (none) none
7月 21 08:49:55 zktecon wpa_supplicant[18227]: dbus: Failed to construct signal
7月 21 09:11:24 zktecon wpa_supplicant[18227]: rfkill: WLAN soft blocked
7月 21 09:11:25 zktecon wpa_supplicant[18227]: nl80211: deinit ifname=wlx7cdd90caf78b disabled_11b_rates=0
7月 21 09:12:31 zktecon wpa_supplicant[18227]: dbus: wpa_dbus_get_object_properties: failed to get object properties: (none) none
7月 21 09:12:31 zktecon wpa_supplicant[18227]: dbus: Failed to construct signal

what 's problems?

**Comment by andrew-bibb** [comment]
It looks like right here:

`21 09:11:24 zktecon wpa_supplicant[18227]: rfkill: WLAN soft blocked`

As root or super user unblock it from a terminal:
`rfkill unblock all`

I'm not that familiar with the workings of wpa_s so you may need to restart the service after  removing the soft block.
