### ISSUE TITLE
DBus NoReply Error

### ISSUE THREAD

**Issue by bwinkler** [andrew-bibb/cmst#175]
When connecting/disconnecting a VPN using the menu from the system tray icon, a popup warning message displays saying:

We received a DBUS reply message indicating an error.
Error Name:
org.freedesktop.DBus.Error.NoReply

However, the VPN action completes successfully and likewise the commands work fine from connmanctl without error.

**Comment by andrew-bibb** [comment]
Should be fixed now. Thank you for reporting it.
