### ISSUE TITLE
appstream-metadata legacy format and location

### ISSUE THREAD

**Issue by agaida** [andrew-bibb/cmst#176]
```
W: cmst: appstream-metadata-in-legacy-location usr/share/appdata/cmst.appdata.xml
E: cmst: appstream-metadata-legacy-format usr/share/appdata/cmst.appdata.xml
```
Hi, some lintian whining - unfortunately lintian is right most of the time: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by andrew-bibb** [comment]
Thanks for finding and reporting this.  Think I have it fixed and have uploaded the changes here.  Anything else let me know.
