### ISSUE TITLE
A new icon definition file message

### ISSUE THREAD

**Issue by caadar** [andrew-bibb/cmst#177]
Every time CMST started the following message appears:

> A new icon definition file will be installed to
> <$HOME>/.config/cmst/cmst.icon and a backup of the old definition file
> has been created as <$HOME>/.config/cmst/cmst.icon.N
>
> If the original definition file was customized and you wish to retain
> those changes you will need to manually merge them into the new file.
>
> If the original was never customized or you just wish to delete the
> backup now you may select Discard to delete the backup or Save to
> retain it.

Regardless of save or discard, number N increases only.

If CMST started in terminal:

> qt5ct: using qt5ct plugin
> qt5ct: D-Bus system tray: no

Floating message appears. After save or discard is selected terminal also shows:

> CMST - Error reply received to GetCapabilities method: Missing method-call handler at path /org/freedesktop/Notifications interface org.freedesktop.Notifications name GetCapabilities

Dispite this CMST works as expected.

CMST: 2017.03.18
System: Gentoo
WM: Stumpwm
Tray: trayer

**Comment by caadar** [comment]
Number N increases only if save button pressed of course.

**Comment by andrew-bibb** [comment]
This almost sounds like a permissions problem. There are a whole lot of debug lines which should print to the terminal if there were any file creation or remove errors. You are not seeing any of those.

Can you post the [IconManager] section of `~/.config/cmst/cmst.conf` on your system.  I want to check the hash against the one shipped.  If they don't match that is the issue.  Problem then will be figuring out why they don't.

**Comment by caadar** [comment]
Yeah, it was a permissions problem: cmst.conf was owned by root:root, user could read it only. Fixed.
