### ISSUE TITLE
cmst spams "No carrier" to session log

### ISSUE THREAD

**Issue by Coacher** [andrew-bibb/cmst#179]
Hello.

I have cmst-git @ 5417fb438b54f7210c33e93861415789f0a5adf4
Right after start cmst starts spamming to the session log "No carrier" message.
I have bluetooth and wifi disabled and ethernet cable plugged 100% of times.
Not sure what carrier cmst expects.

**Comment by Coacher** [comment]
cmst spams a new message every 3-5 seconds. This is very annoying :(

**Comment by andrew-bibb** [comment]
Can you give me the exact line you are seeing?  Sorry, but also not sure what you mean by session log, so where are you finding this?  I actually don't know all that much about the inner workings, logging, etc. of Linux, so pointing me in the direction of where you are seeing this would be helpful.

We do log a selected few items to the system log.  All of these except for one related to VPN (if someone compiled ConnMan without VPN support) will also throw up a warning message box.  I assume you are not seeing that box?

**Comment by Coacher** [comment]
Exact line is `"No carrier"` including quotes.
By session log I mean `~/.xsession-errors`. The exact location varies though, e.g. sddm stores this file as `.local/share/sddm/xorg-session.log`. Just the usual log file to store all messages in a user session.

I'm not seeing this box, I don't use VPN and I have `Disable VPN` ticked in cmst preferences.

**Comment by andrew-bibb** [comment]
Thanks, that helped.  Seems the xsession-errors file is mainly used from display managers.  I start X automatically at boot, so I put in a redirect to file for errors and tried it but I'm not getting any errors at all. 

I did a grep for "No Carrier" in the CMST source code and the only time that term is used is in the CMST source file "tr_strings.cpp" and in the resulting translation files.  It is for an error string returned by ConnMan.  The only time I would use it is if I was presenting that information to the user in a dialog, which does not seem to be occurring.  I also checked using grep for any debug statements which would write to stderr and while there are a few I didn't see anywhere "No carrier" could be a possible return value (text to be displayed was hard coded in).

Somewhat selfish, but can you shutdown CMST while leaving ConnMan running.  If you have it minimized in the system tray just right click the icon and exit.  Then see if the messages stop.  If they do then definitely something I've got going on, but darned if I can figure out what at the moment. If the messages persist then not CMST, maybe ConnMan or something with your display manager.

**Comment by Coacher** [comment]
After I exit cmst, the messages continue to appear. I can confirm, cmst process isn't present.
So, this is RESOLVED INVALID?

**Comment by andrew-bibb** [comment]
We can just close it, no need to mark it with anything.  I'm wondering if this is even a ConnMan issue.  I think ConnMan only returns the "No carrier" error as a DBus message (which is where I would catch it).  Curious though what else could be sending a message like that, and why.

**Comment by andrew-bibb** [comment]
Closing
