### ISSUE TITLE
Start cmst minimized at startup

### ISSUE THREAD

**Issue by cswl** [andrew-bibb/cmst#180]
How can I create a startup entry to start cmst minimized..

I like the icon tray of cmst but I have to open it and minizme manually everytime.

**Comment by andrew-bibb** [comment]
Actually a variety of ways depending on what sort of desktop environment, if any, you are running.  If you are already autostarting and just need to have it minimized at start probably the easiest is to go into the Preferences tab and put a check in the "Start Minimized" checkbox under Start Options (right hand column, 5 items down).

If you are not now autostarting and you are using some sort of DE (KDE, Gnome, XFCE, etc), and would like to autostart then putting a check in the lowest left box (Enable Autostart) will put a desktop entry in your local ~/.config/autostart directory.  From there you can either edit the .desktop entry to use the -m or --minimized command line options, or more simply start the program then check the "Start Minimized" box as described above.  Next time you start it should be minimized to the tray.

**Comment by andrew-bibb** [comment]
Closing
