### ISSUE TITLE
roothelper save error

### ISSUE THREAD

**Issue by Ilya87** [andrew-bibb/cmst#185]
My OS is Arch Linux x86_64
I made chmod -R 711 for my user home directory, I am in network group, but cmst roothelper denies to save changes (asks for super user priveleges)
![cmst error](https://user-images.githubusercontent.com/1446573/39068845-6f35b072-44e6-11e8-8859-31d796ddf25c.png)

**Comment by andrew-bibb** [comment]
Not ignoring this, I Just got back late last night from 10 days in Japan.  Getting back into the swing of things around here. I'm in the process (as in right now) of updating my Arch system. I want to see if I can reproduce this error.  It used to work just fine.  It is likely permissions, but if you are in the network group it should work so something is not right.  

Back to you in a bit (maybe a day or two).  I'll probably be asking if certain files are where they are supposed to be.  I thought I had this documented, but looking for answers it seems a bit loose (or maybe just jet lag on my part). I need to make sure I get a full list of what is supposed to be where so we can do it all in one shot. Then I'll make sure to document it in the wiki.

**Comment by Ilya87** [comment]
Now it works. It seems to me that I added my user to the network group and then didn't restart cmst.
