### ISSUE TITLE
missing README.md in tarball

### ISSUE THREAD

**Issue by martinkg** [andrew-bibb/cmst#188]
missing README.md in tar archive.
https://github.com/andrew-bibb/cmst/archive/cmst-2018.01.06.tar.gz

**Comment by andrew-bibb** [comment]
Don't think I've ever included it, mainly wanted to have people read it here.  That being said, I don't see any reason why I can't have it in the tarball. I'll see about adding it in.

Thanks for reporting it.

**Comment by andrew-bibb** [comment]
Just uploaded the fix. README should be included in the next release tarball
