### ISSUE TITLE
VPN editor access denied

### ISSUE THREAD

**Issue by CityofSirtel** [andrew-bibb/cmst#189]
Fresh Arch install with cmst from AUR, the VPN editor appears to not have access to the roothelper

DBus Error Name: org.freedesktop.DBus.Error.AccessDenied

String: org.freedesktop.DBus.Error.AccessDenied

Message: Rejected send message, 1 matched rules; type="method_call", sender=":1.21" (uid=1000 pid=526 comm="cmst -session 23ab6d1ce-4521-4262-9df7-cc81b9b32ca") interface="org.cmst.roothelper" member="getFileList" error name="(unset)" requested_reply="0" destination="org.cmst.roothelper" (bus)

I tried changing the policy group as seen here, no luck
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893276

edit: just tried installing from git with the qmake DISTRO=arch command same problem

**Comment by andrew-bibb** [comment]
Are you a member of the "network" group?  On a bare bones Arch installation you may need to create the group first then join it.  Don't forget to restart after creating and joining.  The "netdev" group in your link is for Debian.  Every distribution seems to have their own name for the group allowed to control network services, hence the DISTRO= build command.

If you are member of the "network" group we've got bigger problems, but let's try the simple solution first.

**Comment by CityofSirtel** [comment]
Yup that was it sorry

**Comment by andrew-bibb** [comment]
No problem, glad it is working.  The information is mostly in the Wiki here, but the pieces are in separate locations. You obviously made a good attempt to find it and came up empty so I should try to remedy that.  First step will probably be correcting the "mostly" and "separate locations" parts,
