### ISSUE TITLE
iwd support

### ISSUE THREAD

**Issue by gothmog123** [andrew-bibb/cmst#190]
Hi when I use iwd instead of connman, there is a lot of weird behaviour. Do you think it would be possible to make cmst work smoothly with iwd? Thanks.

**Comment by agaida** [comment]
why instead?

**Comment by gothmog123** [comment]
Sorry I mean when I use iwd instead of wpa_supplicant. With connman of course.

**Comment by agaida** [comment]
Ok - there should be no problem - at least my tests was fine and i have at least one happy "customer" with that configuration. Please keep in mind that connman has to be built with --enable-iwd.
See also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=%23896686

**Comment by andrew-bibb** [comment]
There are some ongoing interface  issues between ConnMan and IWD.  See this for instance: https://lists.01.org/pipermail/iwd/2018-August/004717.html

My intention is to have CMST work with ConnMan.  As these issues are ironed out between ConnMan and IWD they should work here. If something does not, for example there is a new or different DBus service call added to ConnMan for IWD then I'll add it to the program.  As far as adding to the program goes, I've put a new note at the top of the readme on the front page you guys may want to check out.  Not dead, just not able to spend a lot of time here lately.

**Comment by librewish** [comment]
when used iwd instead of wpa_supplicant 
i cant see the wifi signal availablity it always shows 0%

**Comment by Vistaus** [comment]
> when used iwd instead of wpa_supplicant
> i cant see the wifi signal availablity (signal strength) it always shows 0%

Same here.

**Comment by andrew-bibb** [comment]
ConnMan 1.38 has a huge number of iwd fixes.  I am using it now and it and seems to be working.
