### ISSUE TITLE
Dbus permissions error

### ISSUE THREAD

**Issue by jamtur01** [andrew-bibb/cmst#191]
I'm seeing an issue where cmst won't let me load VPN configurations.

![screenshot_20180831_002450](https://user-images.githubusercontent.com/4365/44892741-701f7280-acb4-11e8-9f56-9f22d0e8ebad.png)

I've Google'd about and found mention of the Dbus policy needing netdev not network on Debian/Ubuntu but I have that fix in place and I am a member of the netdev group.

```
<busconfig>
    <!-- Only root can own roothelper -->
    <policy user="root">
        <allow own="org.cmst.roothelper"/>
        <allow send_destination="org.cmst.roothelper"
               send_interface="org.cmst.roothelper"/>
    </policy>
    <policy group="netdev">
        <allow send_destination="org.cmst.roothelper"
               send_interface="org.cmst.roothelper"/>
    </policy>
</busconfig>
```

My host is Ubuntu 18.04 running the cmst 2018.01.06-3 amd64 package.

**Comment by jamtur01** [comment]
I installed it via the stock Debian package. The reason I mentioned "the fix" is that Googling around indicated that this error had previously occurred because the wrong group was in the policy. This has regressed before that I can see - so I wanted to mentioned I had confirmed it had not happened again.

**Comment by agaida** [comment]
It was: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=893276
Fix: https://salsa.debian.org/lxqt-team/cmst/commit/9f2f174148924e006ce8c8d95389ae605f0cc1a2

Should be fixed in cmst with https://github.com/andrew-bibb/cmst/pull/182

**Comment by jamtur01** [comment]
So ... my issue is that DESPITE that (see my policy above). I get the same error. I am a bit bewildered as to why it's happening. I'll take another look I guess.

**Comment by MrFoxPro** [comment]
@andrew-bibb I have same exception on my Arch laptop. I tried both AUR packages:
https://aur.archlinux.org/packages/cmst
https://aur.archlinux.org/packages/cmst-git

**Comment by MrFoxPro** [comment]
Seems like adding yourself to group `network` fixes it
`sudo usermod -a -G network foxpro`
