### ISSUE TITLE
VPN configuration is not parsed correctly

### ISSUE THREAD

**Issue by jamtur01** [andrew-bibb/cmst#192]
I have a VPN configured like so:

```
[global]
Name = PN

[provider_l2tp]
Type = L2TP
Name = EL2TP
Host = 1.2.3.4
Domain = vpn.com
Networks =
L2TP.User = xxxx
L2TP.Password = xxxx
```

The VPN details are not displayed in the Details and VPN pages.

![screenshot_20180831_003428](https://user-images.githubusercontent.com/4365/44893121-fe94f380-acb6-11e8-9d90-c0396a01144c.png)

![screenshot_20180831_003437](https://user-images.githubusercontent.com/4365/44893133-28e6b100-acb7-11e8-97d2-af26fe181bd2.png)

P.S. The VPN Editor creates a configuration with `&` scattered in various places. I can log a separate issue for that.

This is on Ubuntu 18.04 / KDE PLasma 5.13 / cmst 2018.01.06-3 amd64 package.

**Comment by andrew-bibb** [comment]
The VPN information seems to displaying mostly correctly now.  Exception is the VPN Provider area which will only fill in if you close CMST then restart.  Connman is not sending that information with their PropertiesChanged signal (I've spent a good deal of time with a dbus inspector to verify that).  I am still trying to determine if there is a different signal I have inadvertently failed to connect to, or if it is a bug in Connman.
