### ISSUE TITLE
Add tab "Virtual Networks" to CMST-header

### ISSUE THREAD

**Issue by EarthlingX** [andrew-bibb/cmst#195]
For users of virtual networks/bridges it would be useful to have one more tab (`Virtual Networks`) in the top bar of CMST:

![screenshot](https://user-images.githubusercontent.com/38689554/45598432-a6a30000-b9cb-11e8-95b3-d53b933009aa.png)

This tab could contain all networks like `vnet0` and similar. Would that be possible?

Thanks a lot for your efforts! :-)

**Comment by andrew-bibb** [comment]
Putting in the tab is not difficult, but what sort of controls would be on it?  I also don't recall virtual networks being separate in ConnMan.  It is however completely possible they are and I just glossed over that part of the documentation.  Assuming we can isolate virtual networks from wifi, vpn, etc. we should be able to put in a tab to at least display them.

First order of business is to make sure I can isolate them (once I get back into a mode where I can spend some real time dealing with the program).  Thank you for the suggestion.

**Comment by EarthlingX** [comment]
Thanks a lot for your kind reply! :-) I think just connecting and disconnecting virtual networks in the new tab should be fine for the beginning.

It could be that `ConnMan` handles virtual networks as `Wired`-connections and just separates them because of their name (`vnet0` instead of `enp0s25`) - I try to figure that out!

**Comment by andrew-bibb** [comment]
Three and a half years later I've finally gotten around to doing some research on this.  VLAN's are displayed by Connman and CMST (I've verified that by testing), but configuring and creating is not handled by Connman.  Described in the mailing list post below: 

https://connman.connman.narkive.com/b4HhV8LP/vlan-support

A VLAN can be turned on and off by toggling the underlying ethernet technology on or off, but that is it.  I have done enough research to know how I could identify a VLAN in the services list but all I would be able to do is have a separate tab to display it.  Doing anything else is beyond the scope of this program which it to provide a GUI front end to Connman.
