### ISSUE TITLE
systrayicon when connected to VPN?

### ISSUE THREAD

**Issue by jat255** [andrew-bibb/cmst#198]
Thanks for CMST! I have not been able to figure out if what I'm seeing is intended behavior or not, but when I connect to a VPN (openvpn, if it matters), the tray icon remains the same (in my case the wifi icon). Is there supposed to be some sort of indication of the VPN connection in the tray icon? The only way I can see if I'm connected (besides the initial notification) is right-clicking, going to VPN, and seeing if my VPN listing is checked. There is no indication of the VPN either hovering over the tray icon, or in the icon itself. It would be really nice if a small lock icon was placed over the default icon when the VPN is connected.

Details of installation:
Operating System: Arch Linux 
KDE Plasma Version: 5.14.4
Qt Version: 5.12.0
KDE Frameworks Version: 5.53.0
Kernel Version: 4.19.8-arch1-1-ARCH
OS Type: 64-bit
CMST installed from latest git checkout via AUR package.

**Comment by andrew-bibb** [comment]
There is supposed to be an icon of a lock once you are connected to a VPN. This however is dependent on ConnMan sorting the Services list properly.  I have seen it on my machine where sometimes it shows a lock and sometimes it does not.  There was a discussion a few months back on the ConnMan developer list about this very thing.  I don't recall a resolution.

Anyway, after connecting to the VPN if the Services list at the bottom of the Status tab does not have the VPN connection at the top of the list you will not get the lock icon.  Connman is supposed to move it automatically once you make the secure connection.  If the VPN connection is at the top of the Services list and you still don't have the icon then it is my issue and I'll be asking for some more information.

**Comment by andrew-bibb** [comment]
Cleaning up here.  I'm seeing a lock icon with VPN so closing this.
