### ISSUE TITLE
Arm cros compile debian beaglebone

### ISSUE THREAD

**Issue by joejond** [andrew-bibb/cmst#199]
Is it possible to cross compile using qt for arm beaglebone diatro debian jessy?

**Comment by andrew-bibb** [comment]
Sorry for the delay in answering, but the answer is I'm not sure.  I've only compiled it on desktops.  That being said I don't see why it would not work provided the necessary QT libraries are available.

One thing I would say is that CMST is really only useful for computers that move around or change networks that they are on.  It is basically to assist users in connecting when they change networks.  It is not required at all to use Connman.  If you are more or less static, and I would think something on an ARM platform would be,  then you can do all the network configuration you need with the Connnan CLI interface and bypass CMST entirely.
