### ISSUE TITLE
Starting CMST

### ISSUE THREAD

**Issue by ghost** [andrew-bibb/cmst#20]
Have no real problems with cmst other than tray issue (which we discussed on arch linux forums). Am trying to figure a way to either start cmst or possibly create a .desktop file or keybind [[should have said in openbox]]. For some reason cmst -i did work for me (once) but since am unable to get it to tray from log in. 

If you need any output or log information then feel free to contact me.

**Comment by andrew-bibb** [comment]
I suspect you are no longer following this since I'm pretty sure that CMST is not in ArchBang anymore, but just wanted to mention that I did manage to finally implement your feature request of 6/21/2014 (yes that is right, 2014 - I'm so far behind it is not funny).

With the 15.03.28 version, current on github, all you need to do is supply the name of the icon theme you wish to use after the -i or --icon-theme command line switch.

**Comment by mrgreen3** [comment]
I really tried very hard to keep gkt+ out of ArchBang, but like systemd so
many packages need it. In the end I decided to go with the easy option and
run with Network Manager. Would have thought with lxqt in main repos now
there will be interest in CMST ;-)

**Comment by andrew-bibb** [comment]
Good luck keeping a toolkit (any toolkit) out.  My primary, not development, system is a USB based system built using Archiso.  I try to keep the image at half a Gig or less, and that is really difficult.  I did CMST in QT as I had used it in the past, and I'd never used GTK.  Thought I could balance adding QT by removing GTK3.  Ha! Ended up with all of them (GTK2, GTK3, and QT5) plus that bloated snake Python needed for Samba. 

I think the user base for CMST is bigger than I imagine.  Right now there are volunteer translators for Russian, Chinese, German, Polish and Italian, so I know there are at least 5 other users.  I kind of like it low key as it allows me to work on whatever I feel like at the moment.  For a while there it was becoming a second job and was not fun anymore.  Calmed down a lot recently and is fun again.

**Comment by mrgreen3** [comment]
Well so far I think I have managed to keep Python out, removing gtk+ is
possible, gtk is needed for most terminals, not sure about qterminal.

Grub takes up a lot of room, as does chrome browser. Pacdep is your friend
:-)

Have given up on a light version of ArchBang as gui girls started moaning.

Let me know when you have something to test, can take a look


On Saturday, March 28, 2015, andrew-bibb <notifications@github.com> wrote:

> Good luck keeping a toolkit (any toolkit) out. My primary, not
> development, system is a USB based system built using Archiso. I try to
> keep the image at half a Gig or less, and that is really difficult. I did
> CMST in QT as I had used it in the past, and I'd never used GTK. Thought I
> could balance adding QT by removing GTK3. Ha! Ended up with all of them
> (GTK2, GTK3, and QT5) plus that bloated snake Python needed for Samba.
>
> I think the user base for CMST is bigger than I imagine. Right now there
> are volunteer translators for Russian, Chinese, German, Polish and Italian,
> so I know there are at least 5 other users. I kind of like it low key as it
> allows me to work on whatever I feel like at the moment. For a while there
> it was becoming a second job and was not fun anymore. Calmed down a lot
> recently and is fun again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/andrew-bibb/cmst/issues/20#issuecomment-87324544>.
>


-- 
Kev
