### ISSUE TITLE
/etc/resolv.conf gets overwritten

### ISSUE THREAD

**Issue by arunvk** [andrew-bibb/cmst#205]
installed this via gnome software and immediately removed it because I wasnt sure why I installed it in the first place. Later I noticed that I lost internet connection. upon investigation I found that /etc/resovl.conf was a blank. I manually added a nameserver entry but the file does not persist. The file gets reset every time I reboot and I have to make an entry every time I reboot. Is there a script that can overwrite this file even after removing the sofware? Iam using fedora 31.

**Comment by andrew-bibb** [comment]
CMST does nothing to resolve.conf. The only thing this program does is interface with Connman, mostly via DBus. Connman I believe will take control of resolve.conf, or at least it takes over the routing.  You said you removed the program, did you remove Connman as well?

**Comment by arunvk** [comment]
I didnt know that connman package was installed as well. I have removed it and its working now. thanks for the reply.
