### ISSUE TITLE
Add WireGuard support

### ISSUE THREAD

**Issue by AsciiWolf** [andrew-bibb/cmst#206]
Intel ConnMan now [supports](https://www.phoronix.com/scan.php?page=news_item&px=ConnMan-WireGuard) WireGuard protocol. It would be great if this support could also be added to cmst.

**Comment by progandy** [comment]
I don't see anything that cmst has to do for basic support. I guess it would be nice to have a menu for wireguard settings in the vpn editor, and maybe an import option for wg-quick configuration files.

**Comment by andrew-bibb** [comment]
There are a handful of configuration options that have been added.  I will be adding these to the VPN provisioning editor. 

ConnMan is doing a release soon (first in about a year) so I'm going to be bringing CMST up to date with that.

**Comment by andrew-bibb** [comment]
VPN provisioning editor code for WireGuard is done and here.  While it is there it will not be visible to a user unless they are running Connman version 1.38 or higher.
