### ISSUE TITLE
Inherit system Qt style

### ISSUE THREAD

**Issue by andrhua** [andrew-bibb/cmst#209]
Currently changing themes in Kvantum has no effect on cmst. While I appreciate robustness of its look, it would be great to have it matching with the rest of the system UI.

**Comment by andrew-bibb** [comment]
I took a look at Kvantum earlier today just to see what it is.  I'm running a pretty bare bones system so this is going to be interesting to try and figure out.  May need to set up a virtual machine, but before that can you give some details of what your system is.  What desk top environment for instance, how you installed CMST, which distro you are using.

Thanks

**Comment by andrhua** [comment]
Actually nevermind. I took a closer look at kvantummanager configuration and found that `export QT_STYLE_OVERRIDE=kvantum` variable should be exported. I never did that because other apps somehow picked up custom Qt styling.
