### ISSUE TITLE
feature request: iwd standalone

### ISSUE THREAD

**Issue by gothmog123** [andrew-bibb/cmst#215]
Is there any chance you might be able to implement an iwd standalone mode without connman?

IWD can do dhcp and if I'm using it standalone without any network manager I actually get better bandwidth. I think IWD does some additional magic with dhcp and routing that optimizes wifi connections.

**Comment by andrew-bibb** [comment]
Year and a half later and I'm finally getting around to answering this, sorry about the delay.  Been a crazy time these past two years as I'm sure you are aware.

It would have to be a completely new program to manage it and I'm afraid I'm not really interested in starting something new.  Honestly having too much trouble keeping up with my other projects (not all are programming related either).  Connman does supposedly work with IWD and I've tried it out on two separate occasions, but even recently I've found it to be pretty buggy compared to wpa_supplicant.
