### ISSUE TITLE
SIGSEGV on ethernet re-connection

### ISSUE THREAD

**Issue by andrhua** [andrew-bibb/cmst#217]
Since recently cmst crashes after ethernet cable replugging (or equally, toggling _Powered_ state in Technologies)
`fish: “cmst &” terminated by signal SIGSEGV (Address boundary error)`
Not really sure what could have caused this, `connmanctl monitor on`  output looks fine to me:
```
Service      ethernet_d481d75b5b85_cable Domains = [  ]
Manager                           State = ready
Service      ethernet_d481d75b5b85_cable State = configuration
Technology   ethernet             Connected = False
Manager                           State = idle
Service      ethernet_d481d75b5b85_cable State = disconnect
Service      ethernet_d481d75b5b85_cable Timeservers = [  ]
Service      ethernet_d481d75b5b85_cable Domains = [  ]
Service      ethernet_d481d75b5b85_cable Proxy = [  ]
Service      ethernet_d481d75b5b85_cable State = idle
Service      ethernet_d481d75b5b85_cable Nameservers = [  ]
Manager      ServicesChanged      = {

}, {
removed                  /net/connman/service/ethernet_d481d75b5b85_cable
}
Technology   ethernet             Connected = True
Manager                           State = ready
Manager      ServicesChanged      = {
*AR Wired                ethernet_d481d75b5b85_cable
}, {
}
Service      ethernet_d481d75b5b85_cable Timeservers = [  ]
Service      ethernet_d481d75b5b85_cable State = online
Manager                           State = online
```
Happens both in i3 and bspwm, with and without custom Qt theme, on latest stable Arch kernel 5.8.1-1.
```
cmst --version
CMST - Connman System Tray 2020.04.12-1
```

**Comment by andrew-bibb** [comment]
I've tried power on/off and plugging/unplugging the Ethernet cable, with and without the notification daemon and system tray notifications toggled and I can't duplicate this. I'm also running Arch although on 5.8.3.  Can you start cmst from a terminal (shutdown any running instances first) then try to trigger the error.  If it happens post the output you get to the terminal.

**Comment by andrhua** [comment]
Strangely enough but bug seems to disappear with 5.8.3 kernel
