### ISSUE TITLE
Bulgarian translation 

### ISSUE THREAD

**Issue by mkkDr2010** [andrew-bibb/cmst#219]
For a private project I have made a Bulgarian translation based on german .ts file. I also made a .qm file for testing and after new compilation of cmst successfully testet it.  Do you have interest of that translation? When yes, then please send me a new empty .ts file. I noticed that some option are not translated, because of missing source. For example I didn't find the source of Enable Start Option from GUI.
With regards 
![screen](https://user-images.githubusercontent.com/75447241/101992622-0ffe4000-3cb5-11eb-94a7-c54336ddd08f.jpg)

**Comment by andrew-bibb** [comment]
Sure I'm interested, thank you for the offer.  It has been a while since I've done any work on the translation files. I've got a few things going on at the moment but I hopefully can pull something together and send it along.  Might be a week or two (or three).

**Comment by stefonarch** [comment]
I'm using cmst for years but was not aware that there are translations implemented...

I'm the maintainer of https://translate.lxqt-project.org/, we have also inserted some LXQt-related projects (qlipper, featherpad, kvantum).
If you're interested I could  add cmst, you'll get PR request from LXQBot when new translations are coming in.

**Comment by andrew-bibb** [comment]
stefonarch

Thank you, sounds fine.  Right now our changes are mostly coming from the ConnMan end when they release and update some features. Tough to keep the translations up to date with that, but most things would be good.  

A-

**Comment by stefonarch** [comment]
https://translate.lxqt-project.org/projects/andrew-bibb/cmst/

If you create an account I can give you admin rights on cmst. 
License MIT is ok? 
There are several snippets to display in README.md#translations like that:

<a href="https://translate.lxqt-project.org/engage/andrew-bibb/?utm_source=widget">
<img src="https://translate.lxqt-project.org/widgets/andrew-bibb/-/multi-auto.svg" alt="Translation status" />
</a>

Configure the  bot for PR's is to do but should be ready soon.
