### ISSUE TITLE
Wireless access point deselected after refresh

### ISSUE THREAD

**Issue by BenWestcott** [andrew-bibb/cmst#226]
In the "Wireless" tab, the list of access points, at least on my system, updates itself every few seconds. If I have selected an access point, after the list is updated, the access point is deselected, even if it is still present in the list and has not changed position.

This can be irritating when trying to connect, disconnect, or remove a network, as often the list will refresh in between the time I select the access point and the time I click the button, instead resulting in a "No Services Selected" error.

**Comment by andrew-bibb** [comment]
Thank you for reporting this, I'll check it out.  There has been a lot of activity on the ConnMan developer mailing list past few weeks about updating and selecting services not working so looks like I'll need to go back and read those in more detail. If it is something that is wrong at my end I'll try to fix it. 

In case you were not aware this project is not associated in any way with ConnMan.  All we do is provide a UI to the network manager, although we have branched out slightly with the Provisioning and VPN editors.

**Comment by BenWestcott** [comment]
Unless you are performing some action when I click on the service but not any buttons, this seems like a UI issue, where redrawing the list clears the current selection.
The annoyance occurs because the list is redrawn and the selection is cleared in between the time I click on the service and the time I click an action button.
So when the action button is clicked nothing is selected to perform the action on, because what I had selected a moment ago is no longer selected.
