### ISSUE TITLE
GUI request: agent dialog smaller (scrollable)

### ISSUE THREAD

**Issue by nXecure** [andrew-bibb/cmst#242]
Hi.

First, thank you for this great software. I use and prefer it as my default GUI for managing connman.

I would like to request to make the Agent input window smaller. This could be done making its contents inside a QScrollArea or with a toggle button to show/hide advanced options below the "PreviousPassphrase" entry box. A lot of users I know have small resolution screens and cannot get to the "OK" button (which is hidden under the screen) to make connman accept the passphrase. They normally don't know how to move the window, so they end up frustrated that they cannot get to connect to their wifi.

Do you think this change would be good or could be accepted? It would make the Agent input window smaller, vertically, and it could fit the window better on screens with small resolution size.

Thanks for your time.

**Comment by andrew-bibb** [comment]
Thank you for the suggestion.  I've added scroll bars to the Agent dialog and the changes have been uploaded here.  Next formal release will have this in it.
