### ISSUE TITLE
Could you please clarify some of my questions about translation?

### ISSUE THREAD

**Issue by marcelocripe** [andrew-bibb/cmst#245]
Hi Andrew-Bibb.

Thank you for developing and maintaining the CMST.

I have been reviewing the existing translations for a few days (or weeks) and translating the various phrases and texts that are not translated into the pt_BR language of the CMST at https://translate.lxqt-project.org/translate/andrew-bibb/cmst /pt_BR/.

Could you please clarify some of my doubts?
I have some doubts about what should or should not be translated, for example, entries that have texts joined together, that is, texts without spaces, as in:
WireGuard.Address
VPNC.DeviceType
WireGuard.AllowedIPs

Besides these examples that I mentioned above, there are others that are very similar, are they commands to be done in the terminal window?

Are there commands to be done in the terminal window that shouldn't be translated?

With which text editor can I open the cmst_pt_BR.qm file?

The translate.lxqt site has a lot of glitches and is missing some translations I had done, can I give you a cmst_pt_BR.ts file containing the translations in pt_BR?

Please wait for me to complete the translation, then I intend to review the translation I made for you to make the final merge.

Grateful.

marcelocripe
(Original text in Brazilian Portuguese)

- - - - -

Olá Andrew-Bibb.

Obrigado por desenvolver e manter o CMST.

Eu estou há alguns dias (ou semanas) revisando as traduções existentes e traduzindo as diversas frases e textos que estão sem tradução para o idioma pt_BR do CMST em https://translate.lxqt-project.org/translate/andrew-bibb/cmst/pt_BR/.

Por favor, poderia esclarecer algumas dúvidas minhas sobre tradução?
Eu estou com algumas dúvidas do que deve ou não deve ser traduzido, por exemplo, as entradas que possuem textos aglutinados, ou seja, textos sem espaço, como ocorre em:
WireGuard.Address
VPNC.DeviceType
WireGuard.AllowedIPs

Além destes exemplos que eu citei acima, existem outros que são muito semelhantes, por acaso são comandos para serem feitos na janela de terminal?

Existem comandos para serem feitos na janela de terminal que não devem ser traduzidos?

Com qual editor de texto eu posso abrir o arquivo cmst_pt_BR.qm?

O sítio translate.lxqt apresenta muitas falhas e está perdendo algumas traduções que eu havia feito, eu posso te fornecer um arquivo cmst_pt_BR.ts contendo as traduções em pt_BR?

Por favor, aguarde eu concluir a tradução, depois eu pretendo revisar da tradução que eu fiz para você fazer a mesclagem final.

Grato.

marcelocripe
(Texto original em Português do Brasil)

**Comment by marcelocripe** [comment]
What will be displayed in place of %1?
In the sentence:
'Unable to find a connection to the system bus.<br><br>%1 will not be able to communicate with connman.'
I need to know what %1 is to use Article 'A' or 'O' at the beginning of the sentence.

Grateful.

marcelocripe

- - - - -

O que será exibido no lugar de %1?
Na frase:
'Unable to find a connection to the system bus.<br><br>%1 will not be able to communicate with connman.'
Eu preciso saber o que é %1 para usar o Artigo 'A' ou 'O' no início da frase. 

Grato.

marcelocripe

**Comment by andrew-bibb** [comment]
Marcelocripe,

Thank you for the inquiry.  I am not familiar with the way LXQT works for translations.  The editor intended to be used for translations is QT Linguist, or from the command line **linguist**.  Here is a link to the online documentation: https://doc.qt.io/qt-5/qtlinguist-index.html.  This opens up GUI editor where you can see the strings to be translated, sometimes also the context of where string is used (if I provided it), and track what is finished and not.  I just opened up the  pt_BR.ts file and it looks like this is almost complete.  I don't have a hard number here but I'm guessing 90% or more.

You are more than welcome to do a pull request on a .ts file when you are finished.  If you would prefer to email it to me direct we can do that as well: ajbibb@outlook.com.  If you've done most or all of this translation and would like to be credited let me know, I put the translators names in the "About CMST" box.  I've never been good with language (even English) so I consider that on par with programming ability.

Your question about %1, etc: the value of the argument is in code and is displayed if you use Qt Linguist.  In your example the phrase represents the string "cmst".  That is not always the case, but it is for your example.  There is no easy answer to this question, it will vary from instance to instance.  Generally any arg() supplied with a % would not need to be translated, however you are not asking about translations, you are asking about articles and the only way I think will be to look at the code.

**Comment by marcelocripe** [comment]
Hello dear Andrew-Bibb,

I appreciate your reply.

"I've never been good with language (even English) so I consider that on par with programming ability."
I also don't master the English language. If you agree, we can continue these conversations via email, if you can tell me your native language, I can send you the machine translations of the internet translator from my language into your language directly. It may be that this facilitates communication.

Grateful.
marcelocripe
(Original text in Brazilian Portuguese)

- - - - -

Olá caro Andrew-Bibb, 

Eu agradeço por sua resposta.

"I've never been good with language (even English) so I consider that on par with programming ability."
Eu também não domino o idioma Inglês. Se você concordar, poderemos continuar estas conversas através do e-mail, se você puder me informar o seu idioma natal, eu posso te enviar as traduções automáticas do tradutor da internet do meu idioma para o seu idioma diretamente. Pode ser que isso facilite a comunicação.

Grato.
marcelocripe
(Texto original em Português do Brasil)

**Comment by andrew-bibb** [comment]
Marcelocripe,

I apologize, was going to close this realized I never responded to your last post.  As I mentioned above you may email me direct or send me your .ts file via email. My native (and only I'm afraid) language is English.  I've actually been spending the past week or two revising the translation build code.  Things I used to have to do by hand are not automated so all I have to do is replace an old .ts file with a new one and it will automatically be picked up and built in.
