### ISSUE TITLE
[Bug] System tray cannot show up in waybar if it's specified in sway conf

### ISSUE THREAD

**Issue by IceAsteroid** [andrew-bibb/cmst#298]
It works by being launched in a terminal, the system tray appears in waybar without any issue, but if I specify it in sway conf, such as follows:

exec_always "pkill cmst; cmst -m"

cmst's tray weirdly doesn't show up in waybar, but instead is running in background.

If I then execute cmst in a terminal, the cmst interface will be launched, and the output in terminal will complain "Another running instance of CMST has been detected.  This instance is aborting".

sway version: 1.8.1
waybar version: v0.9.20
cmst version: 2023.03.14-1

Running in voidlinux.

Any ideas?

**Comment by oniGino** [comment]
sounds like waybar is being launched after cmst, that might be the source of the issue, try

`exec_always "pkill cmst; sleep 10; cmst -m"` to verify


either that or your exec environment under sway is missing some ENV variables to let QT know its running under wayland not X

**Comment by IceAsteroid** [comment]
@oniGino
It works, oh my god, thank you so much for the help
