### ISSUE TITLE
Tooltips Popup Text Barely Visible With GTK Themes

### ISSUE THREAD

**Issue by ghost** [andrew-bibb/cmst#37]
Hi Andrew,

I just compiled cmst with QT 5.3.2

I just noticed that the Tooltip popup windows, the text is barely visible, even in a lot of light and dark colored gtk themes. Some themes, regardless of how light or dark, the text isn't even visible at all, the popup just appears empty.

**Comment by andrew-bibb** [comment]
This has been quiet for over a year so I'm going to close it out.
