### ISSUE TITLE
CMST - Connman System Tray Located in /tmp

### ISSUE THREAD

**Issue by ghost** [andrew-bibb/cmst#42]
Hi Andrew,

Something new I see going on is this 'CMST - Connman System Tray' located in /tmp

When you get some free time, can you please change this so it runs in; ~/.config/cmst?

**Comment by moulei** [comment]
Strange, I thought we tried all this...

I'll try and report back...

**Comment by andrew-bibb** [comment]
Don't bother. Realized I still had a bare bones OpenBox virtual machine for the tray icon testing, so tried this out on that.  The lock file disappears when CMST is closed, but if you logout of OpenBox the file remains.  I'll need to see if his happens with XFCE and/or MATE as well.

**Comment by moulei** [comment]
Ok...

Yes if I close cmst it's removed, but I log out of Openbox it stays...

Have fun! :)

**Comment by andrew-bibb** [comment]
Been playing around with this issue on and off and I've come to the conclusion that it has to do with needing a session manager running.  Not a CMST issue, so closing.
