### ISSUE TITLE
Wifi Services & SSID don't appear

### ISSUE THREAD

**Issue by ghost** [andrew-bibb/cmst#46]
Hi Andrew,

So I'm not sure if this is a connman issue or cmst, but when I click the Wifi on, nothing appears for the Services under the Status tab, and nothing appears as well under the Wireless tab.

I've been turning the Wifi on while the Wired is on, I'm assuming Wifi services should show up if the Wired is on?

I have to turn the wifi on and off several times and then sometimes it appears, or I restart cmst with the Wired off, then I turn Wifi on and it works, there's no rhyme or reason, I just play with it as many was as I can think of to make the Wifi services and ssid appear, but I have to play with it a lot to get it to work... hmm

**Comment by moulei** [comment]
I don't know if this happened in older versions, right now I have the latest git...

I just noticed when I turn wifi on and I leave it sit for a few minutes and I haven't connected to any wifi networks, on the Status - Services and under the Wireless tab, they will all disappear...

Hmm odd...

**Comment by moulei** [comment]
Hi Andrew,

I finally got a hold of the developer and he replied to the report, so I hope can please jump on that report too and give some input.

https://01.org/jira/browse/CM-670

THANKS

**Comment by andrew-bibb** [comment]
Really don't think there is anything else I can help with so I'm closing this for now.

**Comment by andrew-bibb** [comment]
Abusing my owner privileges here - no update but an observation.

I've got Connman/CMST installed on a system on a bootable USB.  Tried it in three different machines and in 2 of them WiFI comes right up immediately after toggling power.  On the third the behavior as described above.  Takes forever and sometimes you need to toggle several times.

The only variable changed is the actual computer the USB is plugged into so this looks to be a hardware issue.  This is going to stay closed here as there is absolutely nothing I can do about it.

**Comment by NTohan** [comment]
Hey Guys,

I'm also facing the same issue! D0 you guys know already any fix or workaround for the same ?

I'm using ubuntu16.04 LTS. I did install last stable connman version (1.21) listed in apt-get. It of course replaced network-manager and after a restart I am trying to connect to wifi but then I am facing the same issue where I am not able to see available networks after 

tohan@tohan:~$ connmanctl enable wifi
Enabled wifi
tohan@tohan:~$ connmanctl scan wifi
Error /net/connman/technology/wifi: No carrier
 
Things I have tried so far 
1. restarting connmand.service
2. Installing latest connman(connman-1.32)
3. wpa_supplicant -u
4. Installing connman on an another machine to check if it is a hardware issue

Nothing has worked out so far. It does work with luck sometimes when you keep playing with enable, scan and disable sequence. But I need to develop a software using connman and after trying it for the first time I am not sure if its a good idea :D

Few people are also facing the same issue but I couldn't find any official bug reported though.

Please let me know if you how to make it work.

Thanks in advance.

Cheers,
NTohan

**Comment by andrew-bibb** [comment]
I'm afraid not, and to be honest I was really only interested in the CMST end of it all, and this appears to an issue somewhere else.    

Between you and me, I'm not sure how often the ConnMan bug tracker is checked or even used.  My suggestion would be to post a question on the ConnMan developer mailing list.  I'm subscribed to that and the devs seem to answer questions along these lines very promply.  The output as you posted above I'm sure they will want to see, and they'll probably ask for some log files. Based on observations of the ML I'm pretty sure the devs only check, or at least respond, Monday through Friday.

**Comment by dragon788** [comment]
I believe some of this may be related to dbus/policykit issues. If you would install the gnome desktop environment and use connman from within it I'd imagine it works pretty consistently but if you set up i3/awesome/etc that aren't a standard desktop environment and you don't launch it from gdm or similar then they don't always trigger/open a system-wide dbus session which is how many apps need to communicate. I'm running into the same on 16.04 starting from a server install on my laptop with i3, I'm going to see about adding gdm and registering i3 via a dbus session and will see if that helps.

**Comment by andrew-bibb** [comment]
Thank you for taking an interest in this issue.  I would very much appreciate it if you were able to spend some time tracking this down.  Want to say though that I run a bare bones i3 setup with no DM and the system bus always starts up.  That is on an Arch Linux installation.  Also CMST should throw an error and pop up a dialog when it starts if it cannot make a connection to the system bus.  I don't want to dissuade you from investigating, but just pointing out what does and should happen.

I'm going to reopen this issue so others can see it on the main page.

Thanks again,
A-
