### ISSUE TITLE
Feedback: Tooltips & What's This

### ISSUE THREAD

**Issue by moulei** [andrew-bibb/cmst#82]
Hi Andrew,

To make life easier, you should just ditch the ```Enable ToolTips (Interface)``` & ```What's This```

Remember too on another bug, What's this popups I still can't read, and the tooltips, well popups I'm not sure people are a fan off, like browsers LOL... :)

I'd just put all this information in the man page or docs, the gui is starting to get to busy, besides, putting all this in the man or docs, I'd think that would be easier for you to maintain?

Personally I've never seen tooltips or a what's this in a network manager before, maybe I'm wrong, NetworkManger could have these, but I don't think you want to start getting bloated like NM, hehe...

Keep up the great work...

**Comment by andrew-bibb** [comment]
What's this is the primary method of delivering help to the user.  

Based on your previous suggestion (which I agree with) I have already removed all the tooltips on static elements.  Only ones left in the Interface, or at least the ones I recall, are for the icons in the connected column in the WiFi tab, and to display the name of the notification daemon should one be found (hover over the Notification Daemon text in the preferences tab).  Both are to display dynamic information so don't lend themselves to putting in a man page or other help manual. In the new Start Options under the Preferences tab I do have tooltip text to display the command line option for each start option item, but I've pretty much decided I don't like it and plan to remove it.  

Actually very simple for me to put either or both in, really just a right click on the widget in Designer.   There is some memory hit for filiing them with text, but not a huge amount as space for the QString class, both tooltips and whats this, is allocated with the widget whether or not I fill them up.  Memory for the actual string contents is allocated dynamically,  but the QString class for tooltips and whats this is in memory for each widget no matter what.      

I've still got the theme issues on my radar, both popups and notification one.

**Comment by moulei** [comment]
Well I always thought man was really the primary method of delivering help to the user in Linux...

Hmm

BUT, ok if you say doing this in cmst or man is just as easy, what I'm trying to drive you back to, is that this is not working on my box, with the what's this not showing the text. So now I think, this is more complicated and involved then just typing text in man... See my point now? :)

I still say keep it even simpler, cause there are still bugs with this in the gui and just place it all in man and make your life easier. :)

**Comment by andrew-bibb** [comment]
Understand, but at the moment removing features that work fine is not making things easier.  My opinion on these is if someone does not want to use them then they don't need to.

Theaming issues I'm thinking are just that, theaming issues, and not something in my code.  I'm still planning to look at them, and in my XFCE test system I've got a place to start as I'm seeing it with one specific theme.  

I'm going to close this one out for now.
