### ISSUE TITLE
Doublespace in String

### ISSUE THREAD

**Issue by Sqozz** [andrew-bibb/cmst#88]
This is just a trivial bug but i noticed it while translating the strings. Since you're in a string freeze i did not send a pull request and rather open this bug to log the issue.
Anyway, line 331 of apps/cmstapp/code/agent/ui/agent.ui contains the string:
"Use  the Firefox browser."
Between the "Use" and "the" there is one extra space.

Greetings,
Sqozz

**Comment by andrew-bibb** [comment]
I may string unfreeze, at least short term.  I've just received another pull request that has some user strings changed, but it is a good add.  In the process of reviewing it, and if it is good I'll make this change at the same time.

For translations running lupdate will merge anything you've translated already so no work will be lost.  String freeze was for translators, but there was a hidden reason to buy me some time to look at a few other things that have been accumulating in my "todo" pile.

**Comment by andrew-bibb** [comment]
Changed my mind, string freeze is still in effect.  As much as I like this new dialog from the recent pull request it will be part of the next release.

**Comment by andrew-bibb** [comment]
For the current release I'll modify the en_US translation to deal with with.

For the next release, branch "devel" on GitHub, the string has actually been replaced.
