### ISSUE TITLE
devel branch: agent fails to call RequetBrowser

### ISSUE THREAD

**Issue by hagabaka** [andrew-bibb/cmst#90]
In devel branch, cmst fails to show the request browser dialog, and prints the following error:
```
QMetaObject::invokeMethod: No such method ConnmanAgent::RequestBrowser(QDBusObjectPath,QString)
                                   Candidates are:
                                       RequestBrowser(QString)
                                       RequestBrowser()
```

I think the cause is 03056ad8d5116df9cf583a22d2e7748222d9c483 which removed the QDBusObjectPath parameter, but did not change apps/cmstapp/code/agent/org.monkey_business_enterprises.agent.xml, which says
```
    <method name="RequestBrowser">
      <arg type="o" direction="in"/>
      <arg type="s" direction="in"/>
    </method>

```

**Comment by andrew-bibb** [comment]
That hack in the devel branch was just so we could test the browser dialog with a button click.  It actually broke more things than you list here (and probably more than I know about).  

I'll take a look at your pull, but maybe easiest for me to revert the changes which is what I had planned to do when we were finished with the broswer dialog.
