### ISSUE TITLE
support for IEEE8021x

### ISSUE THREAD

**Issue by excalibur1234** [andrew-bibb/cmst#96]
when i try to connect to wps or psk protected wifi network, i see a "agent input" window. i have to enter security information before i can connect.

when i try to connect to a IEEE8021x protected wifi network, i do not see a "agent input" window and i cannot connect to the network.

**Comment by excalibur1234** [comment]
i actually think this is a problem of connman and not CMST.

please reopen this issue, if you can tell me something about it.

**Comment by andrew-bibb** [comment]
Been away for a week and just got back.

Have you followed the Wiki page for IEE802 networks (link below)?

https://github.com/andrew-bibb/cmst/wiki/Eduroam-and-IEEE802x

The way Connman works you need to have a provisioning file created before you try and connect using the agent.  CMST has the ability to assist in creating this file for you.

**Comment by excalibur1234** [comment]
thanks for your feedback. it looks interesting.

i am almost sure, there is a problem with connman, because i have used connmanctl directly to connect to wifi networks. look here to read more: 
https://github.com/surlykke/lxqt-connman-applet/issues/3
